// types.ts
// Shapes for the SimpleChat JSON APIs the V2 UI consumes.
//
// These mirror what the Flask routes actually return, verified against
// route_backend_conversations.py, route_backend_chats.py and functions_conversation_feed.py.
// Objects that carry far more server-side detail than the UI needs are typed loosely with
// an index signature rather than being modelled exhaustively, so a backend addition never
// breaks the build.

export type Json = Record<string, unknown>;

export interface Conversation {
    id: string;
    title: string;
    last_updated?: string;
    created_at?: string;
    /** Server field name. Pin state is toggled server-side, not set by the client. */
    is_pinned?: boolean;
    is_hidden?: boolean;
    /** Set when an assistant reply arrived that the user has not seen yet. */
    has_unread_assistant_response?: boolean;
    classification?: string | string[] | null;
    /** 'collaborative' conversations live in a different container and have their own APIs. */
    conversation_kind?: string;
    [key: string]: unknown;
}

/** Response shape of GET /api/conversations/feed. */
export interface ConversationFeedPage {
    success: boolean;
    conversations: Conversation[];
    has_more: boolean;
    next_cursor: string | null;
    page_size: number;
    hidden_count: number;
    priority_count: number;
    recent_count: number;
    source_offsets: Record<string, number>;
    search_term?: string;
    include_hidden?: boolean;
}

/**
 * `file` only ever arrives from a shared conversation.
 *
 * `serialize_collaboration_message` (functions_collaboration.py) overrides the stored role
 * with a *display* role of `file` or `image` when the message carries an upload, so a
 * shared thread can contain a role the personal endpoints never emit.
 */
export type MessageRole = 'user' | 'assistant' | 'system' | 'safety' | 'image' | 'file';

export interface ChatMessage {
    id: string;
    conversation_id: string;
    role: MessageRole;
    content: string;
    timestamp?: string;
    model_deployment_name?: string;
    agent_display_name?: string;
    augmented?: boolean;
    metadata?: Json;
    /**
     * Image messages carry their image in `content`, not in a dedicated field.
     *
     * `hydrate_image_messages` (functions_image_messages.py) rewrites `content` to either a
     * `data:image/...` URI for small inline images or the path `/api/image/<message_id>` when
     * the bytes live in blob storage or exceed the inline limit. An externally hosted image
     * arrives as a plain http(s) URL. There is no `image_url` key on the payload.
     *
     * An image generated by approving a ```simpleimage proposal additionally carries
     * `metadata.image_proposal`: the normalised proposal plus `approved_at` and
     * `source_assistant_message_id`. That last field is what lets the image be shown inside
     * the proposal card in the assistant message that suggested it, rather than as a loose
     * bubble at the end of the thread. See `lib/imageProposalSpec.ts`.
     */
    /** Set locally when the user rates a response, so the control reflects their choice. */
    feedbackType?: 'positive' | 'negative';
    /** Reasoning steps captured while this message was streaming. */
    thoughts?: ThoughtEntry[];
    [key: string]: unknown;
}

export interface ModelOption {
    /** Value posted back as `model_deployment`. */
    option_value?: string;
    selection_key?: string;
    deployment_name?: string;
    display_name?: string;
    model_endpoint_id?: string;
    [key: string]: unknown;
}

export interface AgentOption {
    name?: string;
    display_name?: string;
    scope_type?: string;
    description?: string;
    selection_key?: string;
    [key: string]: unknown;
}

export interface PromptOption {
    id?: string;
    name?: string;
    content?: string;
    scope_type?: string;
    [key: string]: unknown;
}

export interface WorkspaceDocument {
    id?: string;
    document_id?: string;
    file_name?: string;
    title?: string;
    abstract?: string;
    /** Stored as an array, but older records and form round-trips can leave a string. */
    authors?: string[] | string;
    keywords?: string[] | string;
    publication_date?: string;
    percentage_complete?: number;
    status?: string;
    document_classification?: string;
    tags?: string[] | string;
    version?: number;
    num_chunks?: number;
    number_of_pages?: number;
    file_size?: number;
    file_type?: string;
    upload_date?: string;
    last_updated?: string;
    revision_family_id?: string;
    is_current_version?: boolean;
    /** Entries are `"<user id>,<approval status>"`, not bare ids. */
    shared_user_ids?: string[];
    shared_approval_status?: 'owner' | 'approved' | 'not_approved' | 'none' | string;
    owner_id?: string;
    user_id?: string;
    created_from_chat_upload?: boolean;
    conversation_id?: string;
    conversation_title_at_upload?: string;
    conversation_url?: string;
    /** `read` is the standard extraction, `layout` the enhanced one. */
    document_intelligence_extraction_mode?: string;
    enhanced_citations?: boolean;
    _ts?: number;
    [key: string]: unknown;
}

/**
 * Response of GET /api/documents.
 *
 * `total_count` is the size of the whole filtered set, not of the page, so it is what the
 * pager counts against. The endpoint has used both `documents` and `items` as its collection
 * key, so both are accepted.
 */
export interface DocumentListResponse {
    documents?: WorkspaceDocument[];
    items?: WorkspaceDocument[];
    page?: number;
    page_size?: number;
    total_count?: number;
    file_downloads_enabled?: boolean;
    needs_legacy_update_check?: boolean;
}

/**
 * Response of GET /api/documents/facets.
 *
 * Counted server-side over the caller's whole workspace and deliberately ignoring the
 * current filters: these drive a navigation rail, and a rail that re-counted itself against
 * the active filter would collapse to zeroes as soon as anything in it was selected.
 */
export interface DocumentFacets {
    total: number;
    untagged: number;
    processing: number;
    errors: number;
    recent: number;
    shared_with_me: number;
    by_tag: Record<string, number>;
    by_classification: Record<string, number>;
}

/** The standing views in the explorer rail. Sent to the API as `place`. */
export type DocumentPlace =
    | 'all'
    | 'recent'
    | 'shared'
    | 'processing'
    | 'errors'
    | 'untagged';

/**
 * Fields the list endpoint will order by.
 *
 * Mirrors ALLOWED_DOCUMENT_SORT_FIELDS in functions_documents.py. Anything outside this set
 * is silently replaced with `_ts` server-side, so a column offering a sort not listed here
 * would appear to work and quietly do nothing.
 */
export type DocumentSortField =
    | '_ts'
    | 'file_name'
    | 'title'
    | 'upload_date'
    | 'file_size'
    | 'number_of_pages'
    | 'version'
    | 'document_classification';

export type SortDirection = 'asc' | 'desc';

/** Everything that decides which documents are shown, and in what order. */
export interface DocumentQuery {
    place: DocumentPlace;
    search: string;
    /** Applied with AND: a document must carry every selected tag. */
    tags: string[];
    classification: string | null;
    page: number;
    pageSize: number;
    sortBy: DocumentSortField;
    sortOrder: SortDirection;
}

/** A named query pinned in the rail. The flat-tag answer to folders. */
export interface DocumentSavedView {
    id: string;
    name: string;
    query: Pick<DocumentQuery, 'place' | 'search' | 'tags' | 'classification'>;
}

/** How the explorer is presented. Persisted through `v2DocumentsPrefs`. */
export interface DocumentExplorerPrefs {
    viewMode: 'details' | 'tiles';
    pageSize: number;
    detailsPaneOpen: boolean;
    columns: string[];
    sortBy: DocumentSortField;
    sortOrder: SortDirection;
}

/**
 * A workspace tag as returned by /api/documents/tags.
 *
 * build_workspace_tags_from_counts returns objects, not strings:
 * [{'name': 'tag1', 'count': 5, 'color': '#3b82f6'}, ...]
 */
export interface WorkspaceTag {
    name: string;
    count?: number;
    color?: string;
}

/**
 * Entities behind the personal workspace sections.
 *
 * Every one of these routes returns more fields than the list views read, and several add
 * fields over time, so each type is deliberately open. Only the fields the UI actually
 * renders or sends are named; anything else stays available through the index signature
 * rather than being dropped on the way through.
 */
export interface WorkspacePrompt {
    id: string;
    name?: string;
    content?: string;
    created_at?: string;
    updated_at?: string;
    [key: string]: unknown;
}

export interface WorkspaceIdentity {
    id: string;
    name?: string;
    description?: string;
    auth_type?: string;
    username?: string;
    scope_type?: string;
    scope_id?: string;
    created_at?: string;
    updated_at?: string;
    [key: string]: unknown;
}

export interface WorkspaceSyncSource {
    id: string;
    name?: string;
    source_type?: string;
    identity_id?: string;
    remote_path?: string;
    enabled?: boolean;
    sync_interval_minutes?: number;
    created_at?: string;
    updated_at?: string;
    [key: string]: unknown;
}

export interface WorkspaceSyncRun {
    id: string;
    source_id?: string;
    status?: string;
    started_at?: string;
    completed_at?: string;
    triggered_by?: string;
    [key: string]: unknown;
}

export interface WorkspaceAgent {
    id: string;
    name?: string;
    display_name?: string;
    description?: string;
    instructions?: string;
    /** True for agents supplied by an administrator, which a user may not edit or delete. */
    is_global?: boolean;
    is_group?: boolean;
    agent_type?: string;
    tags?: string[];
    actions_to_load?: string[];
    [key: string]: unknown;
}

export interface WorkspaceAction {
    id: string;
    name?: string;
    displayName?: string;
    description?: string;
    /** Which connector this action is, for example `mcp`, `openapi` or `sql_query`. */
    type?: string;
    endpoint?: string;
    is_global?: boolean;
    [key: string]: unknown;
}

export interface WorkspaceWorkflow {
    id: string;
    name?: string;
    description?: string;
    status?: string;
    active_run_id?: string | null;
    created_at?: string;
    updated_at?: string;
    [key: string]: unknown;
}

export interface WorkspaceWorkflowRun {
    id: string;
    workflow_id?: string;
    status?: string;
    started_at?: string;
    completed_at?: string;
    [key: string]: unknown;
}

export interface WorkspaceModelEndpointModel {
    id?: string;
    deploymentName?: string;
    modelName?: string;
    displayName?: string;
    enabled?: boolean;
    [key: string]: unknown;
}

export interface WorkspaceModelEndpoint {
    id: string;
    name?: string;
    provider?: string;
    enabled?: boolean;
    connection?: Record<string, unknown>;
    auth?: Record<string, unknown>;
    models?: WorkspaceModelEndpointModel[];
    [key: string]: unknown;
}

/** Where a cited document lives, from functions_citation_tracking._scope_from_citation. */
export interface UsedDocumentScope {
    type?: 'personal' | 'group' | 'public' | string;
    id?: string;
    name?: string;
}

/**
 * A document-level citation aggregate, as built by
 * functions_citation_tracking.build_used_documents and stored on the conversation.
 */
export interface UsedDocument {
    category?: string;
    document_id: string;
    title?: string;
    file_name?: string;
    classification?: string;
    scope?: UsedDocumentScope;
    chunk_ids?: string[];
    citation_ids?: string[];
    page_numbers?: (number | string)[];
    sheet_names?: string[];
    citation_locations?: Array<Record<string, unknown>>;
    [key: string]: unknown;
}

/**
 * Generated conversation summary, present once one has been produced.
 *
 * The body is under `content`, not `text` (route_backend_conversation_export.py builds
 * `{'content', 'model_deployment', 'generated_at', 'message_time_start',
 * 'message_time_end'}`).
 */
export interface ConversationSummary {
    content?: string;
    generated_at?: string;
    model_deployment?: string;
    message_time_start?: string;
    message_time_end?: string;
    [key: string]: unknown;
}

/**
 * Response of GET /api/conversations/<id>/metadata.
 *
 * Field names are taken from the route itself. Note the identifier key is
 * `conversation_id`, not `id`, and the response carries no `created_at`, `participants`
 * or permission flags.
 */
export interface ConversationMetadata {
    conversation_id: string;
    title: string;
    user_id?: string;
    last_updated?: string;
    classification?: string[] | string;
    context?: unknown[];
    tags?: Array<Record<string, unknown>>;
    used_documents_tracking_version?: number | null;
    legacy_used_documents?: UsedDocument[];
    used_documents?: UsedDocument[];
    strict?: boolean;
    is_pinned?: boolean;
    is_hidden?: boolean;
    has_unread_assistant_response?: boolean;
    last_unread_assistant_message_id?: string | null;
    last_unread_assistant_at?: string | null;
    scope_locked?: boolean | null;
    locked_contexts?: unknown[];
    chat_type?: string | null;
    workflow_id?: string | null;
    summary?: ConversationSummary | null;
    linked_workspace_documents?: UsedDocument[];
    [key: string]: unknown;
}

/* -------------------------------------------------------------------------- */
/* Shared (collaborative) conversations                                        */
/* -------------------------------------------------------------------------- */

/**
 * The value `conversation_kind` takes for a shared conversation.
 *
 * Shared conversations are stored in their own Cosmos containers and served by
 * `/api/collaboration/*`. Every personal conversation route either 404s on them or, worse,
 * answers 200 with nothing: `/api/get_messages` turns its `LookupError` into
 * `{'messages': []}`, which is why a shared thread used to open as an empty chat rather
 * than as an error. Routing is therefore decided by this field, never inferred from a
 * failed request.
 */
export const COLLABORATION_KIND = 'collaborative';

/** Chat types a shared conversation can have. Mirrors `collaboration_models.py`. */
export const PERSONAL_MULTI_USER_CHAT_TYPE = 'personal_multi_user';
export const GROUP_MULTI_USER_CHAT_TYPE = 'group_multi_user';

/** Membership lifecycle, from `collaboration_models.py`. */
export type MembershipStatus =
    | 'accepted'
    | 'pending'
    | 'declined'
    | 'removed'
    /**
     * Not a stored status. `serialize_collaboration_conversation` synthesises it for a
     * group-visibility conversation the caller can see purely by being in the group, so
     * there is no per-user membership record to read a status from.
     */
    | 'group_member';

export type MembershipRole = 'owner' | 'admin' | 'member';

/** One person in a shared conversation, as `normalize_collaboration_user` returns them. */
export interface CollaborationParticipant {
    user_id: string;
    display_name?: string;
    email?: string;
    role?: MembershipRole | string;
    membership_status?: MembershipStatus | string;
    [key: string]: unknown;
}

/**
 * A shared conversation, from `serialize_collaboration_conversation`.
 *
 * Extends `Conversation` because the feed returns exactly this shape for its collaboration
 * rows, so the rail renders shared and personal conversations from one list.
 *
 * The `can_*` flags are the authority on what the current user may do. They are not
 * derivable in the browser: they fold together membership status, role, visibility mode
 * and whether membership is explicit, and a group-visibility conversation grants posting
 * without any membership record at all. Deriving them client-side would offer controls the
 * server then rejects.
 */
export interface CollaborationConversation extends Conversation {
    chat_type?: string;
    status?: string;
    created_at?: string;
    updated_at?: string;
    last_message_at?: string;
    last_message_preview?: string;
    message_count?: number;
    participant_count?: number;
    pending_invite_count?: number;
    participants?: CollaborationParticipant[];
    accepted_participant_ids?: string[];
    pending_participant_ids?: string[];
    owner_user_ids?: string[];
    admin_user_ids?: string[];
    current_user_role?: MembershipRole | string | null;
    membership_status?: MembershipStatus | string | null;
    can_manage_members?: boolean;
    can_manage_roles?: boolean;
    can_accept_invite?: boolean;
    can_post_messages?: boolean;
    can_delete_conversation?: boolean;
    can_leave_conversation?: boolean;
    visibility_mode?: string;
    group_id?: string | null;
    group_name?: string | null;
    /** The hidden personal conversation the AI actually runs in. */
    source_conversation_id?: string | null;
}

/**
 * Who wrote a message in a shared conversation.
 *
 * Personal conversations have exactly one human, so the classic and V2 interfaces both
 * label user messages "You" without asking. In a shared thread the author matters, and it
 * arrives on the message as `sender` (also copied into `metadata.sender`).
 */
export interface CollaborationMessageSender {
    user_id?: string;
    display_name?: string;
    email?: string;
    [key: string]: unknown;
}

/** What a message is replying to, resolved for display by the client. */
export interface CollaborationReplyContext {
    message_id?: string;
    display_name?: string;
    preview?: string;
    [key: string]: unknown;
}

/**
 * A message in a shared conversation, from `serialize_collaboration_message`.
 *
 * `message_kind` distinguishes a message merely posted to the other participants
 * (`human_message`) from one that asked the AI to answer (`ai_request`) and from the
 * answer itself (`assistant_response`). The `role` field cannot carry that distinction,
 * because a human message and an AI request are both `user`.
 */
export interface CollaborationMessage extends ChatMessage {
    message_kind?: 'human_message' | 'ai_request' | 'assistant_response' | string;
    sender?: CollaborationMessageSender;
    reply_to_message_id?: string | null;
    explicit_ai_invocation?: boolean;
    filename?: string;
    /** Attached by the client, not the server: the replied-to message resolved for display. */
    reply_context?: CollaborationReplyContext | null;
}

/**
 * One frame from `GET /api/collaboration/conversations/<id>/events`.
 *
 * Built by `_build_collaboration_event`. Unlike the chat stream, this one is a real SSE
 * `message` event carrying a JSON envelope, and the discriminator is `event_type`.
 */
export interface CollaborationEvent {
    conversation_id?: string;
    event_type?: string;
    occurred_at?: string;
    payload?: {
        conversation?: CollaborationConversation;
        message?: CollaborationMessage;
        message_id?: string;
        participant?: CollaborationParticipant;
        participants?: CollaborationParticipant[];
        user?: CollaborationParticipant;
        is_typing?: boolean;
        expires_at?: string;
        deleted_by_user_id?: string;
        updated_by_user_id?: string;
        [key: string]: unknown;
    };
    [key: string]: unknown;
}

/** A person who could be invited, from `/api/user/collaboration-suggestions`. */
export interface CollaboratorSuggestion {
    user_id: string;
    display_name?: string;
    email?: string;
    /** Where the suggestion came from: 'recent', 'group', 'local', and so on. */
    source?: string;
    [key: string]: unknown;
}

/**
 * True when a conversation must be driven through the `/api/collaboration/*` endpoints.
 *
 * Accepts anything carrying `conversation_kind` so the same check works on a feed row, a
 * loaded conversation and a metadata response without the caller narrowing first.
 */
export function isCollaborative(
    conversation: Record<string, unknown> | null | undefined,
): boolean {
    return String(conversation?.conversation_kind ?? '').trim() === COLLABORATION_KIND;
}


export interface AdminNavSection {
    id: string;
    label: string;
    icon?: string;
}

export interface AdminNavTab {
    id: string;
    label: string;
    icon?: string;
    sections: AdminNavSection[];
}

export interface AdminNavGroup {
    id: string;
    label: string;
    icon?: string;
    tabs: AdminNavTab[];
}

export interface WorkspaceRef {
    id: string;
    name: string;
}

/** How the AI notice may be dismissed. Mirrors `AI_NOTICE_FREQUENCIES`. */
export type AiNoticeFrequency = 'non_dismissible' | 'every_session' | 'daily' | 'once';

/**
 * The administrator-configured notice shown below the composer.
 *
 * `hash` is a SHA-256 of the message and frequency, computed by `functions_ai_notice.py`.
 * Editing the notice changes the hash, which invalidates every stored dismissal so the new
 * wording is shown again. It is never recomputed in the browser.
 */
export interface AiNoticeConfig {
    enabled: boolean;
    message: string;
    frequency: AiNoticeFrequency;
    hash: string;
    /** Whether the caller's stored dismissal still covers this notice. Server-decided. */
    dismissed: boolean;
}

/** The notice shown while web search is armed, warning that the message leaves the tenant. */
export interface WebSearchNoticeConfig {
    enabled: boolean;
    text: string;
}

/** A trusted page deployed under `custom_pages` and exposed at `/custom/<slug>`. */
export interface CustomPageNavItem {
    slug: string;
    label: string;
    /** A Bootstrap Icons class name, chosen per page in its metadata contract. */
    icon: string;
    url: string;
    open_in_new_tab: boolean;
}

/** An administrator-approved link shown in the navigation rail. */
export interface ExternalLinkNavItem {
    label: string;
    url: string;
}

/**
 * One configurable navigation group.
 *
 * `menu_name` and `force_menu` come from settings so the rail can apply the same rule the
 * server-rendered navigation does: a short list reads better inline, a longer one becomes
 * a named, collapsible menu.
 */
export interface NavGroup<TItem> {
    enabled: boolean;
    menu_name: string;
    force_menu: boolean;
    items: TItem[];
}

/** Response shape of GET /api/v2/bootstrap. Assembled by route_backend_v2.py. */
export interface BootstrapPayload {
    version: string;
    user: {
        id: string;
        display_name: string;
        email?: string;
        is_admin: boolean;
        roles: string[];
    };
    branding: {
        app_title: string;
        hide_app_title: boolean;
        show_logo: boolean;
        logo_url: string | null;
        logo_dark_url: string | null;
        /** Versioned when a custom icon is stored, so a replacement is not served stale. */
        favicon_url: string;
        classification_banner: {
            enabled: boolean;
            text?: string;
            color?: string;
            text_color?: string;
        } | null;
        /** Home page copy. Falls back server-side to the same default the classic UI uses. */
        landing_page_text: string;
        landing_page_alignment: 'left' | 'center' | 'right';
        landing_page_logo_scale_percent: number;
    };
    /**
     * Administrator-configured navigation groups, resolved server-side.
     *
     * Not derivable from `features` or `settings`: custom pages are filtered per page
     * against the caller's roles, and neither the link list nor the menu names are
     * `enable_*` keys.
     */
    navigation: {
        custom_pages: NavGroup<CustomPageNavItem>;
        external_links: NavGroup<ExternalLinkNavItem>;
    };
    features: Record<string, boolean>;
    catalogs: {
        models: ModelOption[];
        agents: AgentOption[];
        prompts: PromptOption[];
        initial_model_selection: ModelOption | null;
    };
    scope: {
        active_group_id: string | null;
        active_group_name: string | null;
        active_public_workspace_id: string | null;
        groups: WorkspaceRef[];
        public_workspaces: WorkspaceRef[];
    };
    admin_nav: AdminNavGroup[];
    /**
     * Administrator-configured chat notices, resolved server-side.
     *
     * Not derivable from `features`: the AI notice's dismissal state depends on a stored
     * record, and the web search notice depends on `web_search_consent_accepted`, which is
     * not an `enable_*` key and so never appears in `features`.
     */
    notices: {
        ai: AiNoticeConfig;
        web_search: WebSearchNoticeConfig;
    };
    /**
     * Which personal workspace sections this user may see.
     *
     * Resolved server-side by functions_workspace_sections, because the answer combines
     * plain settings, app-role checks and governance policy. `features` cannot carry it:
     * it only forwards `enable_*` keys, so `allow_user_agents`, `allow_user_plugins`,
     * `per_user_semantic_kernel` and `allow_user_custom_endpoints` would all be missing,
     * and the file sync and governance checks are not settings keys at all.
     */
    workspace: WorkspaceAvailability;
    /** Sanitized settings. Never contains keys, secrets or connection strings. */
    settings: Json;
}

/** The group a workspace section belongs to, as reported by the server. */
export type WorkspaceSectionGroup = 'knowledge' | 'automation' | 'connections';

export interface WorkspaceSectionAvailability {
    enabled: boolean;
    /** Why the section is unavailable. Null when it is enabled. */
    reason: string | null;
    group: WorkspaceSectionGroup;
}

export interface WorkspaceAvailability {
    enabled: boolean;
    file_sync_enabled?: boolean;
    governance?: Record<string, boolean>;
    sections: Record<string, WorkspaceSectionAvailability>;
}

/**
 * A single decoded SSE frame from POST /api/chat/stream.
 *
 * The server emits `data: {json}\n\n` with the discriminator carried *inside* the JSON as
 * `type`, rather than using SSE `event:` lines. Content deltas and the terminal frame are
 * signalled by the presence of `content` / `done` rather than by a `type` value, which is
 * why almost everything here is optional.
 */
export interface ChatStreamEvent {
    type?:
        | 'thought'
        | 'conversation_metadata'
        | 'user_message_persisted'
        | 'cancelled'
        | 'canceled'
        | string;
    content?: string;
    done?: boolean;
    error?: string;
    partial_content?: string;
    cancelled?: boolean;
    canceled?: boolean;
    conversation_id?: string;
    conversation_title?: string;
    message_id?: string;
    user_message_id?: string;
    message_persisted?: boolean;
    conversation_kind?: string;
    model_deployment_name?: string;
    agent_display_name?: string;
    augmented?: boolean;
    metadata?: Json;
    [key: string]: unknown;
}

/** Request body for POST /api/chat/stream. Field names verified against the Flask route. */
export interface ChatStreamRequest {
    message: string;
    conversation_id?: string | null;
    chat_type?: string;
    /**
     * A model is identified by these four fields together, not by the deployment name
     * alone. `resolve_streaming_multi_endpoint_gpt_config` returns None when the endpoint
     * id is missing, which silently falls back to the legacy single-endpoint client.
     */
    model_deployment?: string;
    model_id?: string;
    model_endpoint_id?: string;
    model_provider?: string;
    agent_selection?: string;
    reasoning_effort?: string;
    hybrid_search?: boolean;
    web_search_enabled?: boolean;
    image_generation?: boolean;
    /** Deep research. Both fields are sent together, matching the existing client. */
    source_review_enabled?: boolean;
    deep_research_enabled?: boolean;
    url_access_enabled?: boolean;
    doc_scope?: string;
    selected_document_id?: string | null;
    selected_document_ids?: string[];
    active_group_id?: string | null;
    active_group_ids?: string[];
    active_public_workspace_id?: string | null;
    active_public_workspace_ids?: string[];
    [key: string]: unknown;
}

export interface Citation {
    citation_id?: string;
    cited_text?: string;
    file_name?: string;
    page_number?: number | string;
    [key: string]: unknown;
}

/**
 * A single reasoning step surfaced by a `type: "thought"` stream frame.
 *
 * `stepType`, `detail` and `activity` are what `serialize_thought_event` actually sends;
 * without them a live run cannot be drawn as staged progress, only as a list of sentences.
 * They are optional because plenty of steps are exactly that.
 */
export interface ThoughtEntry {
    id: string;
    title: string;
    content: string;
    stepType?: string;
    detail?: string;
    /** The staged-work payload, when the step reports one. See `lib/activityLanes.ts`. */
    activity?: Json;
    progress?: Json;
    stepIndex?: number;
}

/**
 * A reasoning step as returned by the persisted-thoughts endpoint.
 *
 * This is NOT the same shape as `ThoughtEntry`, which comes from a live stream frame. The
 * stored record has `step_type` where the live one has `title`, plus timing the stream does
 * not carry. Keys are quoted from `route_backend_thoughts.py`, which passes `activity` and
 * `progress` through as the objects they were stored as.
 */
export interface PersistedThought {
    id?: string;
    message_id?: string;
    step_index?: number;
    step_type?: string;
    content?: string;
    detail?: string;
    activity?: Json;
    progress?: Json;
    duration_ms?: number | null;
    timestamp?: string;
}

/**
 * A document citation on an assistant message, under `hybrid_citations`.
 *
 * Field names are those `createCitationsHtml` reads in chat-messages.js.
 */
export interface HybridCitation {
    citation_id?: string;
    file_name?: string;
    document_id?: string;
    location_label?: string;
    location_value?: string | number;
    sheet_name?: string;
    page_number?: string | number;
    chunk_id?: string | number;
    /** Present when the citation points at a document summary rather than a passage. */
    metadata_type?: string;
    metadata_content?: string;
    [key: string]: unknown;
}

/** A web result cited by an assistant message, under `web_search_citations`. */
export interface WebCitation {
    url?: string;
    title?: string;
    [key: string]: unknown;
}

/** A tool invocation recorded on an assistant message, under `agent_citations`. */
export interface AgentCitation {
    tool_name?: string;
    function_arguments?: unknown;
    function_result?: unknown;
    timestamp?: string;
    artifact_id?: string;
    [key: string]: unknown;
}
