---
openapi: "3.0.1"
info:
  title: "Knowledge"
  description: "Knowledge APIs for Service Portal"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev222288.service-now.com/"
paths:
  /api/now/knowledge/search/facets:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
