// adminSectionIcons.ts
// Resolve the Bootstrap icon names declared in `admin_settings_nav.py` to local Lucide icons.
//
// The navigation definition is the single source of truth for which icon a group, tab, or
// section carries, and the classic page renders those names directly. V2 draws Lucide
// icons, so this table translates rather than redeclaring an icon per section; a new
// section therefore picks up its icon from the navigation with no change here, as long as
// it reuses a name already listed. `test_v2_admin_section_icons.py` fails when the
// navigation names an icon this table does not translate.

import {
    Activity,
    AppWindow,
    Archive,
    ArrowLeftRight,
    Bell,
    Binoculars,
    BookOpenText,
    Bot,
    Boxes,
    Braces,
    Brush,
    Bug,
    CalendarCheck,
    CalendarClock,
    ChartLine,
    CirclePlay,
    ClipboardCheck,
    Compass,
    Cpu,
    Database,
    DatabaseZap,
    DoorOpen,
    Download,
    ExternalLink,
    Eye,
    FileCheck,
    FileCode,
    Files,
    FileText,
    FileUp,
    Folder,
    Gauge,
    Globe,
    HardDrive,
    HeartPulse,
    History,
    Hourglass,
    House,
    IdCard,
    Image,
    Images,
    Import,
    Info,
    KeyRound,
    Layers,
    LayoutGrid,
    LifeBuoy,
    Lightbulb,
    Link,
    ListChecks,
    ListTree,
    Lock,
    Mail,
    Megaphone,
    MessageSquareHeart,
    MessageSquareMore,
    MessageSquareQuote,
    MessageSquareText,
    Mic,
    Network,
    NotebookText,
    Package,
    Palette,
    Paperclip,
    PenTool,
    Plug,
    Puzzle,
    Quote,
    RefreshCw,
    ScrollText,
    Search,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldX,
    Signpost,
    SlidersHorizontal,
    SlidersVertical,
    Sparkles,
    SquareCheck,
    Star,
    Table,
    Tags,
    User,
    UserCheck,
    UserCog,
    Users,
    Vault,
    Workflow,
    Wrench,
    Zap,
    type LucideIcon,
} from 'lucide-react';

/** Every Bootstrap icon name the admin navigation uses, translated. */
export const ADMIN_NAV_ICONS: Readonly<Record<string, LucideIcon>> = {
    'bi-activity': Activity,
    'bi-archive': Archive,
    'bi-arrow-left-right': ArrowLeftRight,
    'bi-arrow-repeat': RefreshCw,
    'bi-bell': Bell,
    'bi-binoculars': Binoculars,
    'bi-box-arrow-in-down-right': Import,
    'bi-box-arrow-up-right': ExternalLink,
    'bi-box-seam': Package,
    'bi-braces-asterisk': Braces,
    'bi-brush': Brush,
    'bi-bug': Bug,
    'bi-calendar-check': CalendarCheck,
    'bi-calendar-event': CalendarClock,
    'bi-chat-square-dots': MessageSquareMore,
    'bi-chat-square-heart': MessageSquareHeart,
    'bi-chat-square-quote': MessageSquareQuote,
    'bi-chat-square-text': MessageSquareText,
    'bi-check2-square': SquareCheck,
    'bi-clipboard-check': ClipboardCheck,
    'bi-clock-history': History,
    'bi-collection': Boxes,
    'bi-compass': Compass,
    'bi-cpu': Cpu,
    'bi-database': Database,
    'bi-database-exclamation': DatabaseZap,
    'bi-diagram-3': Workflow,
    'bi-door-open': DoorOpen,
    'bi-download': Download,
    'bi-envelope-paper': Mail,
    'bi-eye': Eye,
    'bi-file-earmark-arrow-up': FileUp,
    'bi-file-earmark-check': FileCheck,
    'bi-file-earmark-code': FileCode,
    'bi-file-earmark-richtext': ScrollText,
    'bi-file-earmark-text': FileText,
    'bi-files': Files,
    'bi-folder': Folder,
    'bi-gear-wide-connected': Settings,
    'bi-globe': Globe,
    'bi-graph-up': ChartLine,
    'bi-hdd': HardDrive,
    'bi-hdd-network': Network,
    'bi-heart-pulse': HeartPulse,
    'bi-hourglass-split': Hourglass,
    'bi-house': House,
    'bi-image': Image,
    'bi-images': Images,
    'bi-info-circle': Info,
    'bi-journal-richtext': BookOpenText,
    'bi-journal-text': NotebookText,
    'bi-key': KeyRound,
    'bi-layers': Layers,
    'bi-life-preserver': LifeBuoy,
    'bi-lightbulb': Lightbulb,
    'bi-lightning-charge': Zap,
    'bi-link-45deg': Link,
    'bi-list-check': ListChecks,
    'bi-list-nested': ListTree,
    'bi-lock': Lock,
    'bi-megaphone': Megaphone,
    'bi-mic': Mic,
    'bi-palette': Palette,
    'bi-paperclip': Paperclip,
    'bi-people': Users,
    'bi-person': User,
    'bi-person-badge': IdCard,
    'bi-person-check': UserCheck,
    'bi-person-gear': UserCog,
    'bi-play-circle': CirclePlay,
    'bi-plugin': Plug,
    'bi-puzzle': Puzzle,
    'bi-quote': Quote,
    'bi-robot': Bot,
    'bi-safe': Vault,
    'bi-search': Search,
    'bi-share': Share2,
    'bi-shield-check': ShieldCheck,
    'bi-shield-exclamation': ShieldAlert,
    'bi-shield-lock': Shield,
    'bi-shield-x': ShieldX,
    'bi-signpost-split': Signpost,
    'bi-sliders': SlidersHorizontal,
    'bi-sliders2': SlidersVertical,
    'bi-speedometer2': Gauge,
    'bi-star': Star,
    'bi-stars': Sparkles,
    'bi-table': Table,
    'bi-tags': Tags,
    'bi-tools': Wrench,
    'bi-vector-pen': PenTool,
    'bi-window-plus': AppWindow,
};

/** Drawn for a section the navigation gives no icon, or one this table does not know. */
export const FALLBACK_SECTION_ICON: LucideIcon = Settings2;

/** The "All settings" entry in the category rail, which the navigation does not declare. */
export const ALL_SETTINGS_ICON: LucideIcon = LayoutGrid;

export function resolveAdminNavIcon(name: string | undefined): LucideIcon {
    return (name && ADMIN_NAV_ICONS[name]) || FALLBACK_SECTION_ICON;
}
