# functions_orchestration_images.py
"""Planned image generation for Gather / Reason / Render plans.

Version: 0.261.209
Implemented in: 0.261.138
Refusals for a missing signed-in session reported as their own failure in: 0.261.209

An image the user explicitly asked for is generated by a ``generate_image`` step. Plan
approval is the consent to generate it (in Run automatically mode, the explicit ask is).
The step reuses the chat image path, ``generate_chat_image_message``, so the image is an
ordinary conversation image message tied to the orchestrated answer that will show it,
and the existing inline card, viewer, and editor render it as already generated.

The step also retains an ``image-asset-v1`` result describing the image. Answer steps
place it with ``[[image:<step_id>]]`` tokens, and Render resolves it from that result to
embed the exact image bytes in DOCX, PDF, and PPTX files.

The adapter grants no access of its own: image generation must be enabled, the run's
owner must own the conversation, the prompt passes the chat output checks configured for
answers, and the configured model's own option limits apply.
"""

import logging

from content_screening.contracts import ScreeningError
from functions_analysis_access import AnalysisResultUnavailable, analysis_source_snapshot
from functions_appinsights import log_event
from functions_image_proposals import IMAGE_PROPOSAL_PROMPT_MAX_LENGTH, image_generation_is_enabled
from functions_mixed_source_orchestration import AUTHORIZATION_STATUS_AUTHORIZED, MixedSourceCancellationError
from functions_orchestration_checkpoints import orchestration_answer_message_id
from functions_orchestration_deliverables import AI_ILLUSTRATION_LABEL, image_alt_text
from functions_orchestration_execution_policy import OrchestrationFilePolicyError
from functions_orchestration_result_contracts import (
    IMAGE_ASSET_KIND, IMAGE_ASSET_VERSION, Completeness, Coverage, ResultContractError,
    validate_image_asset_value,
)
from functions_orchestration_result_runtime import (
    raise_source_service_failure, read_complete_input, require_result_service, resolve_step_inputs,
)
from functions_orchestration_results import NamedOutput, ResultUnavailableError
from functions_orchestration_schema import (
    STEP_STATUS_COMPLETED, STEP_STATUS_FAILED, access_failure, build_failure, build_step_result,
    failure_from_exception,
)


_LOG_PREFIX = '[ORCHESTRATION_EXECUTOR]'
_OPTION_NAMES = (('size', 'sizes'), ('quality', 'qualities'), ('background', 'backgrounds'))
_UNAVAILABLE_CODES = frozenset({
    'image_service_unavailable', 'capability_disabled', 'model_configuration_unavailable',
    'model_capability_unavailable', 'unsupported_image_operation', 'unsupported_capability',
    'invalid_model_selection',
})
_PROVIDER_OUTPUT_CODES = frozenset({'image_output_missing', 'image_output_invalid', 'image_download_failed'})


def image_generation_readiness(settings):
    """Whether planned images can be generated now, and the model's exact option values.

    Reads the selected image operation's projection only. No client is built and no
    credential is resolved, so describing a plan never contacts the image service.
    """
    if not image_generation_is_enabled(settings):
        return {'status': 'unavailable', 'reason': 'image_generation_disabled'}
    try:
        # The image route pulls in connection metadata that only image work needs.
        from functions_image_api_route import resolve_selected_image_capability

        capability = resolve_selected_image_capability(settings)
    except Exception as exc:
        log_event(
            '[IMAGE_GENERATION] The configured image model cannot generate planned images.',
            level=logging.WARNING, debug_only=True, extra={'error_type': type(exc).__name__},
        )
        return {'status': 'unavailable', 'reason': 'image_generation_unavailable'}
    # Reference images need the edit operation; without it, images are still generated from prompts.
    try:
        from functions_image_edit import resolve_image_edit_capability
        from functions_image_references import effective_max_reference_images

        edit_capability = resolve_image_edit_capability(settings)
        if not isinstance(edit_capability, dict) or edit_capability.get('enabled') is False:
            edit_capability = {}
        max_reference_images = effective_max_reference_images(edit_capability)
    except Exception as exc:
        log_event(
            '[IMAGE_GENERATION] Reference images are unavailable for planned images.',
            level=logging.WARNING, debug_only=True, extra={'error_type': type(exc).__name__},
        )
        edit_capability, max_reference_images = {}, 0
    return {
        'status': 'available',
        **{plural: [value for value in capability.get(plural) or () if isinstance(value, str)]
           for _name, plural in _OPTION_NAMES},
        'editing': bool(edit_capability.get('editing')) and max_reference_images > 0,
        'max_reference_images': max_reference_images,
        'input_fidelity': edit_capability.get('input_fidelity') is True,
        'input_formats': [value for value in edit_capability.get('input_formats') or () if isinstance(value, str)],
    }


def build_image_prompt(prompt, details=()):
    """The planner's self-contained prompt plus any named visual details, never truncated."""
    parts = [str(prompt or '').strip()]
    for name, text in details:
        text = str(text or '').strip()
        if text:
            parts.append(f'Visual details ({name}): {text}')
    combined = '\n\n'.join(part for part in parts if part)
    if not combined or len(combined) > IMAGE_PROPOSAL_PROMPT_MAX_LENGTH:
        raise ResultContractError('result_input_too_large')
    return combined


def _selected_options(arguments, readiness):
    options = {}
    for name, plural in _OPTION_NAMES:
        value = arguments.get(name) or ''
        if value and value not in readiness.get(plural, ()):
            raise ValueError('The configured image model does not support this image option.')
        options[name] = value
    return options


def _failure(exc):
    """Only application-owned failure codes; never provider or policy text."""
    code = getattr(exc, 'code', None)
    if type(exc).__name__ == 'ImageReferenceError':
        failure = build_failure('image_request_invalid')
        failure['message'] = getattr(exc, 'public_message', None) or failure['message']
        failure['reference_error_code'] = code
        return failure
    if isinstance(exc, OrchestrationFilePolicyError):
        return build_failure('file_publication_not_allowed')
    if isinstance(exc, (ResultUnavailableError, ScreeningError)):
        return access_failure(exc)
    if isinstance(exc, ResultContractError):
        return build_failure('result_input_too_large' if code == 'result_input_too_large' else 'result_invalid')
    if code == 'image_content_refused':
        return build_failure('image_content_refused')
    if code == 'image_rate_limited':
        return build_failure('provider_http_error', provider_status=429)
    if code in _UNAVAILABLE_CODES:
        return build_failure('image_generation_unavailable')
    if code in _PROVIDER_OUTPUT_CODES:
        return build_failure('provider_failed')
    if code == 'invalid_image_request' or isinstance(exc, ValueError):
        return build_failure('image_request_invalid')
    if isinstance(exc, PermissionError):
        return build_failure('image_generation_unavailable')
    return failure_from_exception(exc)


def _failed(failure):
    return build_step_result(
        status=STEP_STATUS_FAILED, failure=failure, summary=failure['message'], error=failure['message'],
    )


def _string_list(value):
    if not isinstance(value, list):
        return []
    out = []
    seen = set()
    for item in value:
        if not isinstance(item, str):
            continue
        text = item.strip()
        if not text or text in seen:
            continue
        seen.add(text)
        out.append(text)
    return out


def _reference_arguments(arguments, seeds):
    """Resolver references for ids the run's server-computed candidates offered, and no others."""
    seeds = seeds if isinstance(seeds, dict) else {}
    documents = {
        item.get('document_id'): item for item in seeds.get('image_reference_documents') or []
        if isinstance(item, dict) and item.get('document_id')
    }
    messages = {
        item.get('message_id'): item for item in seeds.get('image_reference_messages') or []
        if isinstance(item, dict) and item.get('message_id')
    }
    references = []
    document_ids = _string_list(arguments.get('reference_document_ids'))
    for document_id in document_ids:
        candidate = documents.get(document_id)
        if candidate is None:
            raise ValueError('A reference image is unavailable.')
        references.append({
            'type': 'document',
            'document_id': document_id,
            'scope': candidate.get('scope') or 'personal',
            'scope_id': candidate.get('scope_id'),
        })
    for message_id in _string_list(arguments.get('reference_message_ids')):
        if message_id not in messages:
            raise ValueError('A reference image is unavailable.')
        references.append({'type': 'message', 'message_id': message_id})
    return references, document_ids


def _reference_lineage(context, document_ids):
    """Reference documents become result sources, taken from the step's authorized manifest."""
    if not document_ids:
        return []
    manifest = {
        source.get('document_id'): source
        for source in getattr(context, 'execution_manifest', None) or ()
        if isinstance(source, dict)
    }
    sources = []
    for document_id in document_ids:
        source = manifest.get(document_id)
        if source is None or source.get('authorization_status') != AUTHORIZATION_STATUS_AUTHORIZED:
            raise ResultUnavailableError('result_source_unavailable')
        sources.append(source)
    try:
        return analysis_source_snapshot(sources)
    except AnalysisResultUnavailable as exc:
        raise ResultUnavailableError('result_source_unavailable') from exc


def adapter_generate_image(step, context, *, settings, user_id, emit=None, cancel_requested=None):
    """Generate one approved image, persist it with the answer, and retain its descriptor."""
    service = require_result_service(context)
    producer = context.result_producer(step)
    if user_id != producer.user_id or context.plan_contract_version != 2:
        raise ResultUnavailableError('result_owner_mismatch')
    guard_token = context.result_guard_token_for_step(step['step_id'])
    input_fingerprint = context.result_input_fingerprint_for_step(step['step_id'])
    readers = resolve_step_inputs(step, context)
    arguments = step['arguments']
    seeds = getattr(context, 'seeds', None) or getattr(context, 'original_seeds', {}) or {}

    def recheck():
        if callable(cancel_requested) and cancel_requested():
            raise MixedSourceCancellationError('orchestration_generate_image')
        service.access.authorize_producer(producer, for_write=True)
        if context.result_guard_token_for_step(step['step_id']) != guard_token:
            raise ResultUnavailableError('result_attempt_stopped')
        for reader in readers.values():
            reader.recheck()

    try:
        recheck()
        readiness = image_generation_readiness(settings)
        if readiness['status'] != 'available':
            return _failed(build_failure('image_generation_unavailable'))
        options = _selected_options(arguments, readiness)
        reference_request, reference_document_ids = _reference_arguments(arguments, seeds)
        reference_lineage = _reference_lineage(context, reference_document_ids)
        prompt = build_image_prompt(arguments['prompt'], [
            (name, read_complete_input(reader)) for name, reader in readers.items()
        ])
        title = arguments['title'].strip()
        # Chat's output checks apply to this model-written prompt before anything is generated.
        from functions_chat_content_checks import check_chat_content

        if check_chat_content(prompt, 'chat_output', user_id=user_id, settings=settings).decision == 'block':
            return _failed(build_failure('image_content_refused'))
        recheck()
        reference_sources = None
        reference_metadata = None
        if reference_request:
            from functions_image_edit import resolve_image_edit_capability
            from functions_image_references import resolve_image_references, reference_prompt

            resolved = resolve_image_references(
                settings, user_id, context.conversation_id, reference_request,
                resolve_image_edit_capability(settings),
            )
            reference_sources = resolved['sources']
            reference_metadata = {'image_references': resolved['provenance']}
            prompt = reference_prompt(prompt, len(reference_sources))
            recheck()
        # Image clients and chat persistence are loaded only when an image is generated.
        from functions_image_generation import generate_chat_image_message

        generated = generate_chat_image_message(
            settings=settings, user_id=user_id, conversation_id=context.conversation_id,
            prompt=prompt, user_info={'userId': user_id, 'email': getattr(context, 'user_email', None)},
            proposal={
                'version': 1, 'visualId': step['step_id'], 'title': title,
                'description': AI_ILLUSTRATION_LABEL, 'prompt': prompt,
                'visualType': 'illustration', 'context': AI_ILLUSTRATION_LABEL,
                'orchestration': {'run_id': context.run_id, 'step_id': step['step_id']},
            },
            source_assistant_message_id=orchestration_answer_message_id(context.run_id),
            store_in_blob=True, reference_sources=reference_sources,
            extra_metadata=reference_metadata, input_fidelity='high' if reference_sources else '',
            **options,
        )
        recheck()
        message = generated.get('image_message') or {}
        value = validate_image_asset_value({
            'version': IMAGE_ASSET_VERSION, 'asset_id': step['step_id'],
            'message_id': generated['message_id'], 'title': title[:200], 'alt_text': image_alt_text(title),
            'prompt': str(message.get('prompt') or prompt)[:IMAGE_PROPOSAL_PROMPT_MAX_LENGTH],
            'mime_type': generated['mime_type'], 'size_bytes': generated['image_size'],
            'content_sha256': generated['image_sha256'],
            'model': str(generated.get('model_deployment_name') or '')[:200], 'ai_generated': True,
        })
        task = service.persist_task_result(
            producer=producer, role='reason', status='complete',
            outputs=[NamedOutput(
                'image', IMAGE_ASSET_KIND, value,
                Completeness(
                    'complete', 1, 1, Coverage(1, 1, 'items'), 'valid', ('generated_image_digest',), (),
                ),
            )],
            sources=reference_lineage,
            origin='grounded' if readers or reference_lineage else 'generated', guard_token=guard_token,
            upstream=tuple(dict.fromkeys(reader.reference for reader in readers.values())),
            input_fingerprint=input_fingerprint,
        )
        log_event(
            f'{_LOG_PREFIX} Generated a planned image.',
            extra={
                'run_id': context.run_id, 'conversation_id': context.conversation_id,
                'step_id': step['step_id'], 'message_id': generated['message_id'],
            },
        )
        return build_step_result(
            status=STEP_STATUS_COMPLETED, summary=f'Generated an {AI_ILLUSTRATION_LABEL}.',
            task_result=task,
        )
    except MixedSourceCancellationError:
        raise
    except Exception as exc:
        raise_source_service_failure(exc)
        failure = _failure(exc)
        log_event(
            f'{_LOG_PREFIX} A planned image could not be generated.',
            level=logging.WARNING,
            extra={
                'run_id': context.run_id, 'conversation_id': context.conversation_id,
                'step_id': step['step_id'], 'error_type': type(exc).__name__, 'reason_code': failure['code'],
            },
        )
        return _failed(failure)
