# functions_generated_file_approvals.py

"""Owner approval gate for files generated by participants in shared conversations.

Shared conversations are backed by a hidden source conversation owned by the shared
conversation creator, so any generated file a participant asks for is written into the
owner's storage scope. Rather than failing those requests outright, the artifact is written
immediately in a ``pending_approval`` state and only becomes readable once an authorized
approver releases it. Approval is therefore a cheap state flip and the model never re-runs.

Approval state lives on the artifact message metadata so it travels with the artifact and
cannot be bypassed by reaching the download route directly. Approver discovery is handled by
notifications, which avoids a second index that could drift out of sync with the artifact.
"""

import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from config import cosmos_messages_container
from functions_appinsights import log_event
from functions_group import find_group_by_id, get_user_role_in_group
from functions_settings import get_settings


APPROVAL_STATE_PENDING = "pending_approval"
APPROVAL_STATE_APPROVED = "approved"
APPROVAL_STATE_DENIED = "denied"
APPROVAL_STATE_AUTO_DENIED = "auto_denied"

APPROVAL_TERMINAL_STATES = frozenset({
    APPROVAL_STATE_APPROVED,
    APPROVAL_STATE_DENIED,
    APPROVAL_STATE_AUTO_DENIED,
})

APPROVAL_SCOPE_PERSONAL = "personal"
APPROVAL_SCOPE_GROUP = "group"

# Mirrors functions_approvals.TTL_AUTO_DENY_DAYS so both approval surfaces expire alike.
APPROVAL_TTL_DAYS = 3
APPROVAL_TTL_SECONDS = APPROVAL_TTL_DAYS * 24 * 60 * 60

APPROVAL_SETTING_KEY = "require_shared_conversation_file_approval"

# Downloadable deliverables only. Generated images and charts are inline conversation
# rendering, and gating those would make ordinary chat look broken.
APPROVAL_GATED_FILE_EXTENSIONS = frozenset({
    "csv",
    "xlsx",
    "xls",
    "xlsm",
    "docx",
    "pdf",
    "json",
    "xml",
})

GROUP_DOCUMENT_APPROVER_ROLES = ("Owner", "Admin", "DocumentManager")

GENERATED_FILE_APPROVAL_NOTIFICATION_TYPE = "generated_file_approval_pending"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _utc_now_iso() -> str:
    return _utc_now().isoformat()


def _clean(value: Any) -> str:
    return str(value or "").strip()


def _metadata_of(message_item: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    metadata = (message_item or {}).get("metadata")
    return metadata if isinstance(metadata, dict) else {}


def is_generated_file_approval_enabled(settings: Optional[Dict[str, Any]] = None) -> bool:
    """Return whether the approval gate is switched on for this tenant."""
    resolved_settings = settings if isinstance(settings, dict) else (get_settings() or {})
    return bool(resolved_settings.get(APPROVAL_SETTING_KEY, True))


def normalize_approval_file_extension(file_name: str = "", output_format: str = "") -> str:
    """Return the lowercase extension used to decide whether a write is gated."""
    normalized_format = _clean(output_format).lower().lstrip(".")
    if normalized_format:
        return normalized_format
    return os.path.splitext(_clean(file_name))[1].lower().lstrip(".")


def is_approval_gated_file(file_name: str = "", output_format: str = "") -> bool:
    """Return whether this artifact format is a downloadable deliverable needing approval."""
    return normalize_approval_file_extension(file_name, output_format) in APPROVAL_GATED_FILE_EXTENSIONS


def requires_generated_file_approval(
    access_context: Optional[Dict[str, Any]],
    file_name: str = "",
    output_format: str = "",
    settings: Optional[Dict[str, Any]] = None,
) -> bool:
    """Return whether one artifact write must be staged for approval.

    Owners writing into their own conversation are never gated. Only a non-owner participant
    of a shared conversation producing a downloadable deliverable triggers the gate.
    """
    context = access_context if isinstance(access_context, dict) else {}
    if not context or context.get("is_owner", True):
        return False
    if not context.get("collaboration_conversation_id"):
        return False
    if not is_approval_gated_file(file_name, output_format):
        return False
    return is_generated_file_approval_enabled(settings)


def build_generated_file_approval_metadata(
    access_context: Dict[str, Any],
    requester: Optional[Dict[str, Any]] = None,
    requested_at: str = "",
) -> Dict[str, Any]:
    """Build the pending-approval metadata fragment stored on the artifact message."""
    context = access_context if isinstance(access_context, dict) else {}
    requester_info = requester if isinstance(requester, dict) else {}
    normalized_requested_at = _clean(requested_at) or _utc_now_iso()
    expires_at = (
        _utc_now() + timedelta(days=APPROVAL_TTL_DAYS)
    ).isoformat()

    group_id = _clean(context.get("group_id"))
    approval_scope = APPROVAL_SCOPE_GROUP if group_id else APPROVAL_SCOPE_PERSONAL

    return {
        "generated_artifact_approval_required": True,
        "generated_artifact_approval_state": APPROVAL_STATE_PENDING,
        "generated_artifact_approval_scope": approval_scope,
        "generated_artifact_approval_group_id": group_id,
        "generated_artifact_approval_owner_user_id": _clean(context.get("owner_user_id")),
        "generated_artifact_approval_collaboration_conversation_id": _clean(
            context.get("collaboration_conversation_id")
        ),
        "generated_artifact_approval_requested_by_id": _clean(
            requester_info.get("user_id") or requester_info.get("userId") or context.get("user_id")
        ),
        "generated_artifact_approval_requested_by_name": _clean(
            requester_info.get("display_name") or requester_info.get("displayName")
        ),
        "generated_artifact_approval_requested_by_email": _clean(requester_info.get("email")),
        "generated_artifact_approval_requested_at": normalized_requested_at,
        "generated_artifact_approval_expires_at": expires_at,
        "generated_artifact_approval_resolved_by_id": None,
        "generated_artifact_approval_resolved_by_name": None,
        "generated_artifact_approval_resolved_at": None,
    }


def get_generated_file_approval_state(message_item: Optional[Dict[str, Any]]) -> str:
    """Return the approval state recorded on an artifact message, or an empty string."""
    metadata = _metadata_of(message_item)
    if not metadata.get("generated_artifact_approval_required"):
        return ""
    return _clean(metadata.get("generated_artifact_approval_state")).lower()


def generated_file_approval_is_pending(message_item: Optional[Dict[str, Any]]) -> bool:
    """Return whether an artifact is still waiting on an approval decision."""
    return get_generated_file_approval_state(message_item) == APPROVAL_STATE_PENDING


def assert_generated_file_approval_allows_download(
    user_id: str,
    message_item: Optional[Dict[str, Any]],
) -> None:
    """Block artifact content access until an approver has released the file.

    Enforced independently of the tabular export manifest checks so a staged artifact cannot
    be reached by any caller, including the participant who requested it.
    """
    approval_state = get_generated_file_approval_state(message_item)
    if not approval_state or approval_state == APPROVAL_STATE_APPROVED:
        return

    if approval_state == APPROVAL_STATE_PENDING:
        raise PermissionError("This file is waiting for owner approval")
    raise PermissionError("This file was not approved")


def resolve_generated_file_approver_role(
    user_id: str,
    message_item: Optional[Dict[str, Any]],
) -> str:
    """Return how a user qualifies to approve an artifact, or an empty string if they cannot."""
    normalized_user_id = _clean(user_id)
    if not normalized_user_id:
        return ""

    metadata = _metadata_of(message_item)
    if not metadata.get("generated_artifact_approval_required"):
        return ""

    # A requester is never their own approver, whatever else they hold. Without this a group
    # Admin or DocumentManager who is only a participant could stage a file and release it
    # themselves, which would make the gate meaningless for them.
    if _clean(metadata.get("generated_artifact_approval_requested_by_id")) == normalized_user_id:
        return ""

    approval_scope = _clean(metadata.get("generated_artifact_approval_scope")).lower()
    if approval_scope == APPROVAL_SCOPE_GROUP:
        group_id = _clean(metadata.get("generated_artifact_approval_group_id"))
        if not group_id:
            return ""
        group_doc = find_group_by_id(group_id)
        if not group_doc:
            return ""
        group_role = _clean(get_user_role_in_group(group_doc, normalized_user_id))
        allowed_roles = {role.lower() for role in GROUP_DOCUMENT_APPROVER_ROLES}
        if group_role.lower() in allowed_roles:
            return group_role
        return ""

    if _clean(metadata.get("generated_artifact_approval_owner_user_id")) == normalized_user_id:
        return "ConversationOwner"
    return ""


def user_can_approve_generated_file(user_id: str, message_item: Optional[Dict[str, Any]]) -> bool:
    """Return whether a user may approve or deny one staged artifact."""
    return bool(resolve_generated_file_approver_role(user_id, message_item))


def apply_generated_file_approval_decision(
    message_item: Dict[str, Any],
    decision: str,
    resolver: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Record an approval decision on the artifact message and return the updated document.

    Approving also releases the underlying artifact lifecycle so the existing publication
    checks treat the file as readable.
    """
    normalized_decision = _clean(decision).lower()
    if normalized_decision not in APPROVAL_TERMINAL_STATES:
        raise ValueError(f"Unsupported generated file approval decision: {decision}")

    resolver_info = resolver if isinstance(resolver, dict) else {}
    metadata = _metadata_of(message_item)
    if not metadata.get("generated_artifact_approval_required"):
        raise ValueError("Artifact is not gated by an approval")

    current_state = _clean(metadata.get("generated_artifact_approval_state")).lower()
    if current_state in APPROVAL_TERMINAL_STATES:
        raise ValueError("This file approval was already resolved")

    metadata.update({
        "generated_artifact_approval_state": normalized_decision,
        "generated_artifact_approval_resolved_by_id": _clean(
            resolver_info.get("user_id") or resolver_info.get("userId")
        ) or None,
        "generated_artifact_approval_resolved_by_name": _clean(
            resolver_info.get("display_name") or resolver_info.get("displayName")
        ) or None,
        "generated_artifact_approval_resolved_at": _utc_now_iso(),
    })
    message_item["metadata"] = metadata
    return message_item


def build_generated_file_approval_client_payload(
    message_item: Optional[Dict[str, Any]],
    viewer_user_id: str = "",
) -> Dict[str, Any]:
    """Build the approval descriptor the chat UI renders on a gated artifact."""
    approval_state = get_generated_file_approval_state(message_item)
    if not approval_state:
        return {}

    metadata = _metadata_of(message_item)
    normalized_viewer_id = _clean(viewer_user_id)
    requested_by_id = _clean(metadata.get("generated_artifact_approval_requested_by_id"))

    return {
        "state": approval_state,
        "is_pending": approval_state == APPROVAL_STATE_PENDING,
        "scope": _clean(metadata.get("generated_artifact_approval_scope")),
        "requested_by_id": requested_by_id,
        "requested_by_name": _clean(metadata.get("generated_artifact_approval_requested_by_name")),
        "requested_at": _clean(metadata.get("generated_artifact_approval_requested_at")),
        "expires_at": _clean(metadata.get("generated_artifact_approval_expires_at")),
        "resolved_by_name": _clean(metadata.get("generated_artifact_approval_resolved_by_name")),
        "resolved_at": _clean(metadata.get("generated_artifact_approval_resolved_at")),
        "viewer_is_requester": bool(
            normalized_viewer_id and normalized_viewer_id == requested_by_id
        ),
        "viewer_can_approve": bool(
            approval_state == APPROVAL_STATE_PENDING
            and user_can_approve_generated_file(normalized_viewer_id, message_item)
        ),
    }


def list_expired_pending_generated_file_artifacts(limit: int = 200) -> List[Dict[str, Any]]:
    """Return staged artifacts whose approval window has elapsed."""
    normalized_limit = max(1, min(int(limit or 200), 1000))
    query = (
        "SELECT TOP @limit * FROM c "
        "WHERE c.role = 'file' "
        "AND IS_DEFINED(c.metadata.generated_artifact_approval_state) "
        "AND c.metadata.generated_artifact_approval_state = @pending_state "
        "AND IS_DEFINED(c.metadata.generated_artifact_approval_expires_at) "
        "AND c.metadata.generated_artifact_approval_expires_at < @now"
    )
    try:
        return list(cosmos_messages_container.query_items(
            query=query,
            parameters=[
                {"name": "@limit", "value": normalized_limit},
                {"name": "@pending_state", "value": APPROVAL_STATE_PENDING},
                {"name": "@now", "value": _utc_now_iso()},
            ],
            enable_cross_partition_query=True,
        ))
    except Exception as exc:
        log_event(
            "[GENERATED_FILE_APPROVALS] Failed to query expired staged artifacts",
            {"error": str(exc)},
            level=logging.ERROR,
            exceptionTraceback=True,
        )
        return []
