# functions_orchestration_images.py
"""Planned image generation for Gather / Reason / Render plans.

Version: 0.261.138
Implemented in: 0.261.138

An image the user explicitly asked for is generated by a ``generate_image`` step. Plan
approval is the consent to generate it (in Run automatically mode, the explicit ask is).
The step reuses the chat image path, ``generate_chat_image_message``, so the image is an
ordinary conversation image message tied to the orchestrated answer that will show it,
and the existing inline card, viewer, and editor render it as already generated.

The step also retains an ``image-asset-v1`` result describing the image. Answer steps
place it with ``[[image:<step_id>]]`` tokens, and Render resolves it from that result to
embed the exact image bytes in DOCX, PDF, and PPTX files.

The adapter grants no access of its own: image generation must be enabled, the run's
owner must own the conversation, the prompt passes the chat output checks configured for
answers, and the configured model's own option limits apply.
"""

import logging

from content_screening.contracts import ScreeningError
from functions_appinsights import log_event
from functions_image_proposals import IMAGE_PROPOSAL_PROMPT_MAX_LENGTH, image_generation_is_enabled
from functions_mixed_source_orchestration import MixedSourceCancellationError
from functions_orchestration_checkpoints import orchestration_answer_message_id
from functions_orchestration_deliverables import AI_ILLUSTRATION_LABEL, image_alt_text
from functions_orchestration_execution_policy import OrchestrationFilePolicyError
from functions_orchestration_result_contracts import (
    IMAGE_ASSET_KIND, IMAGE_ASSET_VERSION, Completeness, Coverage, ResultContractError,
    validate_image_asset_value,
)
from functions_orchestration_result_runtime import (
    raise_source_service_failure, read_complete_input, require_result_service, resolve_step_inputs,
)
from functions_orchestration_results import NamedOutput, ResultUnavailableError
from functions_orchestration_schema import (
    STEP_STATUS_COMPLETED, STEP_STATUS_FAILED, build_failure, build_step_result, failure_from_exception,
)


_LOG_PREFIX = '[ORCHESTRATION_EXECUTOR]'
_OPTION_NAMES = (('size', 'sizes'), ('quality', 'qualities'), ('background', 'backgrounds'))
_UNAVAILABLE_CODES = frozenset({
    'image_service_unavailable', 'capability_disabled', 'model_configuration_unavailable',
    'model_capability_unavailable', 'unsupported_image_operation', 'unsupported_capability',
    'invalid_model_selection',
})
_PROVIDER_OUTPUT_CODES = frozenset({'image_output_missing', 'image_output_invalid', 'image_download_failed'})


def image_generation_readiness(settings):
    """Whether planned images can be generated now, and the model's exact option values.

    Reads the selected image operation's projection only. No client is built and no
    credential is resolved, so describing a plan never contacts the image service.
    """
    if not image_generation_is_enabled(settings):
        return {'status': 'unavailable', 'reason': 'image_generation_disabled'}
    try:
        # The image route pulls in connection metadata that only image work needs.
        from functions_image_api_route import resolve_selected_image_capability

        capability = resolve_selected_image_capability(settings)
    except Exception as exc:
        log_event(
            '[IMAGE_GENERATION] The configured image model cannot generate planned images.',
            level=logging.WARNING, debug_only=True, extra={'error_type': type(exc).__name__},
        )
        return {'status': 'unavailable', 'reason': 'image_generation_unavailable'}
    return {
        'status': 'available',
        **{plural: [value for value in capability.get(plural) or () if isinstance(value, str)]
           for _name, plural in _OPTION_NAMES},
    }


def build_image_prompt(prompt, details=()):
    """The planner's self-contained prompt plus any named visual details, never truncated."""
    parts = [str(prompt or '').strip()]
    for name, text in details:
        text = str(text or '').strip()
        if text:
            parts.append(f'Visual details ({name}): {text}')
    combined = '\n\n'.join(part for part in parts if part)
    if not combined or len(combined) > IMAGE_PROPOSAL_PROMPT_MAX_LENGTH:
        raise ResultContractError('result_input_too_large')
    return combined


def _selected_options(arguments, readiness):
    options = {}
    for name, plural in _OPTION_NAMES:
        value = arguments.get(name) or ''
        if value and value not in readiness.get(plural, ()):
            raise ValueError('The configured image model does not support this image option.')
        options[name] = value
    return options


def _failure(exc):
    """Only application-owned failure codes; never provider or policy text."""
    code = getattr(exc, 'code', None)
    if isinstance(exc, OrchestrationFilePolicyError):
        return build_failure('file_publication_not_allowed')
    if isinstance(exc, (ResultUnavailableError, ScreeningError)):
        return build_failure('result_unavailable')
    if isinstance(exc, ResultContractError):
        return build_failure('result_input_too_large' if code == 'result_input_too_large' else 'result_invalid')
    if code == 'image_content_refused':
        return build_failure('image_content_refused')
    if code == 'image_rate_limited':
        return build_failure('provider_http_error', provider_status=429)
    if code in _UNAVAILABLE_CODES:
        return build_failure('image_generation_unavailable')
    if code in _PROVIDER_OUTPUT_CODES:
        return build_failure('provider_failed')
    if code == 'invalid_image_request' or isinstance(exc, ValueError):
        return build_failure('image_request_invalid')
    if isinstance(exc, PermissionError):
        return build_failure('image_generation_unavailable')
    return failure_from_exception(exc)


def _failed(failure):
    return build_step_result(
        status=STEP_STATUS_FAILED, failure=failure, summary=failure['message'], error=failure['message'],
    )


def adapter_generate_image(step, context, *, settings, user_id, emit=None, cancel_requested=None):
    """Generate one approved image, persist it with the answer, and retain its descriptor."""
    service = require_result_service(context)
    producer = context.result_producer(step)
    if user_id != producer.user_id or context.plan_contract_version != 2:
        raise ResultUnavailableError('result_owner_mismatch')
    guard_token = context.result_guard_token_for_step(step['step_id'])
    input_fingerprint = context.result_input_fingerprint_for_step(step['step_id'])
    readers = resolve_step_inputs(step, context)
    arguments = step['arguments']

    def recheck():
        if callable(cancel_requested) and cancel_requested():
            raise MixedSourceCancellationError('orchestration_generate_image')
        service.access.authorize_producer(producer, for_write=True)
        if context.result_guard_token_for_step(step['step_id']) != guard_token:
            raise ResultUnavailableError('result_attempt_stopped')
        for reader in readers.values():
            reader.recheck()

    try:
        recheck()
        readiness = image_generation_readiness(settings)
        if readiness['status'] != 'available':
            return _failed(build_failure('image_generation_unavailable'))
        options = _selected_options(arguments, readiness)
        prompt = build_image_prompt(arguments['prompt'], [
            (name, read_complete_input(reader)) for name, reader in readers.items()
        ])
        title = arguments['title'].strip()
        # Chat's output checks apply to this model-written prompt before anything is generated.
        from functions_chat_content_checks import check_chat_content

        if check_chat_content(prompt, 'chat_output', user_id=user_id, settings=settings).decision == 'block':
            return _failed(build_failure('image_content_refused'))
        recheck()
        # Image clients and chat persistence are loaded only when an image is generated.
        from functions_image_generation import generate_chat_image_message

        generated = generate_chat_image_message(
            settings=settings, user_id=user_id, conversation_id=context.conversation_id,
            prompt=prompt, user_info={'userId': user_id, 'email': getattr(context, 'user_email', None)},
            proposal={
                'version': 1, 'visualId': step['step_id'], 'title': title,
                'description': AI_ILLUSTRATION_LABEL, 'prompt': prompt,
                'visualType': 'illustration', 'context': AI_ILLUSTRATION_LABEL,
                'orchestration': {'run_id': context.run_id, 'step_id': step['step_id']},
            },
            source_assistant_message_id=orchestration_answer_message_id(context.run_id),
            store_in_blob=True, **options,
        )
        recheck()
        message = generated.get('image_message') or {}
        value = validate_image_asset_value({
            'version': IMAGE_ASSET_VERSION, 'asset_id': step['step_id'],
            'message_id': generated['message_id'], 'title': title[:200], 'alt_text': image_alt_text(title),
            'prompt': str(message.get('prompt') or prompt)[:IMAGE_PROPOSAL_PROMPT_MAX_LENGTH],
            'mime_type': generated['mime_type'], 'size_bytes': generated['image_size'],
            'content_sha256': generated['image_sha256'],
            'model': str(generated.get('model_deployment_name') or '')[:200], 'ai_generated': True,
        })
        task = service.persist_task_result(
            producer=producer, role='reason', status='complete',
            outputs=[NamedOutput(
                'image', IMAGE_ASSET_KIND, value,
                Completeness(
                    'complete', 1, 1, Coverage(1, 1, 'items'), 'valid', ('generated_image_digest',), (),
                ),
            )],
            sources=[], origin='grounded' if readers else 'generated', guard_token=guard_token,
            upstream=tuple(dict.fromkeys(reader.reference for reader in readers.values())),
            input_fingerprint=input_fingerprint,
        )
        log_event(
            f'{_LOG_PREFIX} Generated a planned image.',
            extra={
                'run_id': context.run_id, 'conversation_id': context.conversation_id,
                'step_id': step['step_id'], 'message_id': generated['message_id'],
            },
        )
        return build_step_result(
            status=STEP_STATUS_COMPLETED, summary=f'Generated an {AI_ILLUSTRATION_LABEL.lower()}.',
            task_result=task,
        )
    except MixedSourceCancellationError:
        raise
    except Exception as exc:
        raise_source_service_failure(exc)
        failure = _failure(exc)
        log_event(
            f'{_LOG_PREFIX} A planned image could not be generated.',
            level=logging.WARNING,
            extra={
                'run_id': context.run_id, 'conversation_id': context.conversation_id,
                'step_id': step['step_id'], 'error_type': type(exc).__name__, 'reason_code': failure['code'],
            },
        )
        return _failed(failure)
